routes/web.php
                ],
            ]);
        });
        Route::resource('club', 'ClubController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //茶會管理
    //權限：tea-party.manage
    Route::group(['middleware' => 'permission:tea-party.manage'], function () {
        Route::post('export/tea-party', 'ExportController@teaParty')->name('export.tea-party');
        Route::resource('tea-party', 'TeaPartyController');
    });
    //網站設定
    //權限：setting.manage
    Route::group(['middleware' => 'permission:setting.manage', 'prefix' => 'setting'], function () {
        Route::get('/', 'SettingController@edit')->name('setting.edit');
        Route::post('update', 'SettingController@update')->name('setting.update');
    });
    //ApiKey管理
    //權限：api-key.manage
    Route::group(['middleware' => 'permission:api-key.manage'], function () {
        Route::resource('api-key', 'ApiKeyController', [
            'except' => [
                'show',
                'edit',
                'update',
            ],
        ]);
    });
    //打卡紀錄管理
    //權限：record.manage
    Route::group(['middleware' => 'permission:record.manage'], function () {
        Route::post('export/record', 'ExportController@record')->name('export.record');
        Route::resource('record', 'RecordController', [
            'only' => [
                'index',
            ],
        ]);
    });

    //抽獎編號展示
    Route::group(['middleware' => 'permission:ticket.manage|ticket.show-ticket'], function () {
        Route::get('ticket/ticket', 'TicketController@ticket')->name('ticket.ticket');
    });
    //抽獎編號管理
    //權限：ticket.manage
    Route::group(['middleware' => 'permission:ticket.manage'], function () {
        Route::get('ticket/info', 'TicketController@ticketInfo')->name('ticket.info');
        Route::post('export/ticket', 'ExportController@ticket')->name('export.ticket');
        Route::resource('ticket', 'TicketController', [
            'only' => [
                'index',
            ],
        ]);
    });
    //工作人員抽獎編號展示
    Route::group(['middleware' => 'permission:extra-ticket.manage|extra-ticket.show-ticket'], function () {
        Route::get('extra-ticket/ticket', 'ExtraTicketController@ticket')->name('extra-ticket.ticket');
    });
    //工作人員抽獎編號管理
    //權限：extra-ticket.manage
    Route::group(['middleware' => 'permission:extra-ticket.manage'], function () {
        Route::get('extra-ticket/info', 'ExtraTicketController@ticketInfo')->name('extra-ticket.info');
        Route::get('extra-ticket/import', 'ExtraTicketController@getImport')->name('extra-ticket.import');
        Route::post('extra-ticket/import', 'ExtraTicketController@postImport')->name('extra-ticket.import');
        Route::get('extra-ticket/download-import-sample', 'ExtraTicketController@downloadImportSample')
            ->name('extra-ticket.download-import-sample');
        Route::delete('extra-ticket/destroy-all', 'ExtraTicketController@destroyAll')->name('extra-ticket.destroy-all');
        Route::resource('extra-ticket', 'ExtraTicketController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //學生抽獎編號展示
    Route::group(['middleware' => 'permission:student-ticket.manage|student-ticket.show-ticket'], function () {
        Route::get('student-ticket/ticket', 'StudentTicketController@ticket')->name('student-ticket.ticket');
    });
    //學生抽獎編號管理
    //權限：student-ticket.manage
    Route::group(['middleware' => 'permission:student-ticket.manage'], function () {
        Route::get('student-ticket/info', 'StudentTicketController@ticketInfo')->name('student-ticket.info');
        Route::get('student-ticket/import', 'StudentTicketController@getImport')->name('student-ticket.import');
        Route::post('student-ticket/import', 'StudentTicketController@postImport')->name('student-ticket.import');
        Route::get('student-ticket/download-import-sample', 'StudentTicketController@downloadImportSample')
            ->name('student-ticket.download-import-sample');
        Route::delete('student-ticket/destroy-all', 'StudentTicketController@destroyAll')
            ->name('student-ticket.destroy-all');
        Route::resource('student-ticket', 'StudentTicketController', [
            'except' => [
                'show',
            ],
        ]);
    });

    //Feedback
    Route::get('my-feedback', 'FeedbackController@my')->name('feedback.my');
    Route::get('feedback/create/{club}', 'FeedbackController@createOrEdit')->name('feedback.create');
    Route::post('feedback/{club}', 'FeedbackController@store')->name('feedback.store');
    Route::post('export/feedback', 'ExportController@feedback')->name('export.feedback');
    Route::resource('feedback', 'FeedbackController', [
        'only' => [
            'index',
            'show',
        ],
    ]);

    //統計
    //權限：stats.access
    Route::group(['middleware' => 'permission:stats.access'], function () {
        Route::get('stats', 'StatsController@index')->name('stats.index');
        Route::get('stats/heatmap', 'StatsController@heatmap')->name('stats.heatmap');
    });

    //問卷
    Route::group(['middleware' => 'permission:survey.manage'], function () {
        //學生問卷
        Route::post('export/student-survey', 'ExportController@studentSurvey')->name('export.student-survey');
        Route::resource('student-survey', 'StudentSurveyController', [
            'only' => [
                'index',
                'show',
            ],
        ]);
        //社團問卷
        Route::post('export/club-survey', 'ExportController@clubSurvey')->name('export.club-survey');
        Route::resource('club-survey', 'ClubSurveyController', [
            'only' => [
                'index',
                'show',
            ],
        ]);
    });
    Route::group(['prefix' => 'survey'], function () {
        Route::get('/', 'SurveyController@index')->name('survey.index');
        Route::get('student/edit', 'SurveyController@createOrEditStudentSurvey')->name('survey.student.edit');
        Route::post('student', 'SurveyController@storeStudentSurvey')->name('survey.student.store');
        Route::get('student', 'SurveyController@showStudentSurvey')->name('survey.student.show');
        Route::get('club/edit', 'SurveyController@createOrEditClubSurvey')->name('survey.club.edit');
        Route::post('club', 'SurveyController@storeClubSurvey')->name('survey.club.store');
        Route::get('club', 'SurveyController@showClubSurvey')->name('survey.club.show');
    });

    //自己的社團
    Route::group(['prefix' => 'own-club'], function () {
        Route::get('edit', 'OwnClubController@edit')->name('own-club.edit');
        Route::patch('update', 'OwnClubController@update')->name('own-club.update');
        Route::get('data-update-request', 'OwnClubController@dataUpdateRequestPanel')
            ->name('own-club.data-update-request.index');
        Route::get('data-update-request/create', 'OwnClubController@createDataUpdateRequest')
            ->name('own-club.data-update-request.create');
        Route::post('data-update-request', 'OwnClubController@storeDataUpdateRequest')
            ->name('own-club.data-update-request.store');
        Route::get('edit-tea-party', 'OwnClubController@editTeaParty')->name('own-club.edit-tea-party');
        Route::patch('update-tea-party', 'OwnClubController@updateTeaParty')->name('own-club.update-tea-party');
        Route::delete('destroy-tea-party', 'OwnClubController@destroyTeaParty')->name('own-club.destroy-tea-party');
    });

    //我的 QR Code
    Route::get('/my-qrcode', 'HomeController@myQRCode')->name('my-qrcode');
    //QR Code 掃描
    Route::get('qr/{code}', 'QrcodeScanController@scan')->name('qrcode.scan');
    Route::get('scan', 'QrcodeScanController@webScan')->name('qrcode.web-scan');
    Route::post('scan-api/{code}', 'QrcodeScanController@webScanApi')->name('qrcode.web-scan-api');
    //條碼圖
    Route::group(['prefix' => 'code'], function () {
        Route::get('qrcode/{code}', 'CodePictureController@qrcode')->name('code-picture.qrcode');
        Route::get('barcode/{code}', 'CodePictureController@barcode')->name('code-picture.barcode');
    });

    //活動紀錄
    Route::middleware('permission:activity-log.access')->group(function () {
        Route::resource('activity-log', 'ActivityLogController')->only(['index', 'show']);
    });
    //會員資料
    Route::group(['prefix' => 'profile'], function () {
        //查看會員資料
        Route::get('/', 'ProfileController@getProfile')->name('profile');
        Route::group(['middleware' => 'local_account'], function () {
            //編輯會員資料
            Route::get('edit', 'ProfileController@getEditProfile')->name('profile.edit');
            Route::put('update', 'ProfileController@updateProfile')->name('profile.update');
            //兩步驟驗證
            Route::group(['prefix' => '2fa'], function () {
                Route::get('/', 'Google2FAController@index')->name('profile.2fa.index');
                Route::post('toggle', 'Google2FAController@toggle')->name('profile.2fa.toggle');
            });
        });
    });
});

//內部API
Route::group(['prefix' => 'api'], function () {
    Route::post('/booth-list', 'ApiController@boothList')->name('api.booth-list');
    Route::post('/user-list', 'ApiController@userList')->name('api.user-list');
    Route::post('/club-student-list', 'ApiController@clubStudentList')->name('api.club-student-list');
    Route::post('/student-list', 'ApiController@studentList')->name('api.student-list');
    Route::post('/club-type-list', 'ApiController@clubTypeList')->name('api.club-type-list');
    Route::post('/club-list', 'ApiController@clubList')->name('api.club-list');
    Route::post('/my-favorite-club-ids', 'ApiController@myFavoriteClubIds')->name('api.my-favorite-club-ids');
    Route::post('/my-feedback-list', 'ApiController@myFeedbackList')->name('api.my-feedback-list');

app/Http/Controllers/StudentTicketController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\StudentTicketsDataTable;
use App\Models\StudentTicket;
use App\Services\FileService;
use App\Services\StudentService;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;
use PhpOffice\PhpSpreadsheet\RichText\RichText;

class StudentTicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  StudentTicketsDataTable  $dataTable
     * @return JsonResponse|Response|View
     */
    public function index(StudentTicketsDataTable $dataTable)
    {
        return $dataTable->render('student-ticket.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('student-ticket.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @param  StudentService  $studentService
     * @return Response
     *
     * @throws ValidationException
     */
    public function store(Request $request, StudentService $studentService)
    {
        $this->validate($request, [
            'id'  => 'nullable|integer|min:1|unique:student_tickets,id',
            'nid' => [
                'required',
                'regex:#^[a-zA-Z]\d+$#',
            ],
        ]);

        $student = $studentService->findByNid($request->get('nid'));
        if (!$student) {
            return back()->withErrors(['nid' => '查無此人'])->withInput();
        }
        if ($student->studentTicket) {
            return back()->withErrors(['nid' => '學號 已經存在。'])->withInput();
        }

        StudentTicket::create(array_merge($request->only('id'), [
            'student_nid' => $student->nid,
        ]));

        return redirect()->route('student-ticket.index')->with('success', '學生抽獎編號已新增');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  StudentTicket  $studentTicket
     * @return Response
     */
    public function edit(StudentTicket $studentTicket)
    {
        return view('student-ticket.edit', compact('studentTicket'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  StudentTicket  $studentTicket
     * @param  StudentService  $studentService
     * @return Response
     *
     * @throws ValidationException
     */
    public function update(Request $request, StudentTicket $studentTicket, StudentService $studentService)
    {
        $this->validate($request, [
            'nid' => [
                'required',
                'regex:#^[a-zA-Z]\d+$#',
            ],
        ]);

        $student = $studentService->findByNid($request->get('nid'));
        if (!$student) {
            return back()->withErrors(['nid' => '查無此人'])->withInput();
        }
        if ($student->studentTicket && $student->studentTicket->id != $studentTicket->id) {
            return back()->withErrors(['nid' => '學號 已經存在。'])->withInput();
        }

        $studentTicket->update(array_merge($request->only('name', 'class'), [
            'student_nid' => $student->nid,
        ]));

        return redirect()->route('student-ticket.index')->with('success', '學生抽獎編號已更新');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  StudentTicket  $studentTicket
     * @return Response
     *
     * @throws Exception
     */
    public function destroy(StudentTicket $studentTicket)
    {
        $studentTicket->delete();

        return redirect()->route('student-ticket.index')->with('success', '學生抽獎編號已刪除');
    }

    /**
     * @return RedirectResponse
     *
     * @throws Exception
     */
    public function destroyAll()
    {
        StudentTicket::query()->delete();

        activity('auth')->by(auth()->user())->log('刪除了 全部的 學生抽獎編號');

        return redirect()->route('student-ticket.index')->with('success', '學生抽獎編號已全數刪除');
    }

    public function ticket()
    {
        return view('student-ticket.ticket');
    }

    public function ticketInfo(Request $request)
    {
        $id = $request->get('id');
        $ticket = StudentTicket::find($id);
        if (!$ticket) {
            $json = [
                'found' => false,
                'id'    => sprintf('%04d', $id),
            ];

            return response()->json($json);
        }
        $json = [
            'found' => true,
            'id'    => sprintf('%04d', $ticket->id),
            'name'  => $ticket->student->name,
            'class' => $ticket->student->class,
        ];

        return response()->json($json);
    }

    public function getImport()
    {
        return view('student-ticket.import');
    }

    /**
     * @param  Request  $request
     * @param  FileService  $fileService
     * @param  StudentService  $studentService
     * @return RedirectResponse
     *
     * @throws ValidationException
     */
    public function postImport(Request $request, FileService $fileService, StudentService $studentService)
    {
        //檢查匯入檔案格式為xls或xlsx
        $this->validate($request, [
            'import_file' => 'required|mimes:xls,xlsx',
        ]);

        $uploadedFile = $request->file('import_file');
        $uploadedFilePath = $uploadedFile->getPathname();
        $spreadsheet = $fileService->loadSpreadsheet($uploadedFilePath);
        if (!$spreadsheet) {
            return redirect()->back()->withErrors(['importFile' => '檔案格式限xls或xlsx']);
        }
        $successCount = 0;
        $skipCount = 0;
        foreach ($spreadsheet->getAllSheets() as $sheetId => $sheet) {
            foreach ($sheet->getRowIterator() as $rowNumber => $row) {
                //忽略第一列
                if ($rowNumber == 1) {
                    continue;
                }
                //該列資料
                $rowData = [];
                for ($col = 1; $col <= 4; $col++) {
                    $cell = $sheet->getCellByColumnAndRow($col, $row->getRowIndex());
                    $colData = $cell->getValue();
                    if (!($colData instanceof RichText)) {
                        $colData = trim($cell->getFormattedValue());
                    }
                    $rowData[] = $colData;
                }
                //資料
                $id = $rowData[0];
                //ID僅接受正整數
                if (!filter_var($id, FILTER_VALIDATE_INT) || $id <= 0) {
                    $id = null;
                }
                $nid = strtoupper($rowData[1]);
                //NID必須填寫
                if (empty($nid)) {
                    $skipCount++;
                    continue;
                }
                //找出學生
                $student = $studentService->findByNid($nid);
                if (!$student) {
                    $skipCount++;
                    continue;
                }
                //建立資料
                try {
                    //刪除相同ID或NID的紀錄
                    StudentTicket::where('id', $id)->orWhere('student_nid', $student->nid)->delete();
                    //新增紀錄
                    StudentTicket::create([
                        'id'          => $id,
                        'student_nid' => $student->nid,
                    ]);
                } catch (Exception $exception) {
                    $skipCount++;
                    continue;
                }

                $successCount++;
            }
        }

        return redirect()->route('student-ticket.index')->with('success', "匯入完成(成功:{$successCount}/跳過:{$skipCount})");
    }

    public function downloadImportSample()
    {
        $path = resource_path('sample/student_ticket_import_sample.xlsx');

        return response()->download($path);
    }
}

resources/views/student-ticket/create.blade.php
@extends('layouts.base')

@section('title', '新增學生抽獎編號')

@section('buttons')
    <a href="{{ route('student-ticket.index') }}" class="btn btn-secondary">
        <i class="fa fa-arrow-left mr-2"></i>學生抽獎編號管理
    </a>
@endsection

@section('main_content')
    <div class="card">
        <div class="card-body">
            {{ bs()->openForm('post', route('student-ticket.store')) }}
            {{ bs()->formGroup(bs()->input('number', 'id')->attributes(['min' => 1])->placeholder('如：1'))->label('抽獎編號')->showAsRow() }}
            @include('student-ticket.form')

            <div class="row">
                <div class="mx-auto">
                    {{ bs()->submit('確認', 'primary')->prependChildren(fa()->icon('check')->addClass('mr-2')) }}
                </div>
            </div>
            {{ bs()->closeForm() }}
        </div>
    </div>
@endsection

resources/views/student-ticket/edit.blade.php
@extends('layouts.base')

@php
    $isEditMode = isset($studentTicket);
    $methodText = $isEditMode ? '編輯' : '新增';
@endphp

@section('title', $methodText . '學生抽獎編號')

@section('buttons')
    <a href="{{ route('student-ticket.index') }}" class="btn btn-secondary">
        <i class="fa fa-arrow-left mr-2"></i>學生抽獎編號管理
    </a>
@endsection

@section('main_content')
    <div class="card">
        <div class="card-body">
            {{ bs()->openForm('patch', route('student-ticket.update', $studentTicket), ['model' => $studentTicket]) }}
            {{ bs()->formGroup(bs()->input('number', 'id')->disabled())->label('抽獎編號')->showAsRow() }}
            @include('student-ticket.form')

            <div class="row">
                <div class="mx-auto">
                    {{ bs()->submit('確認', 'primary')->prependChildren(fa()->icon('check')->addClass('mr-2')) }}
                </div>
            </div>
            {{ bs()->closeForm() }}
        </div>
    </div>
@endsection

resources/views/student-ticket/form.blade.php
{{ bs()->formGroup(bs()->text('nid')->required()->placeholder('如：M0402935'))->class('required')->label('學號')->helpText('必須為本學期在校學生')->showAsRow() }}

resources/views/student-ticket/index.blade.php
@extends('layouts.base')

@section('title', '學生抽獎編號管理')

@section('buttons')
    <a href="{{ route('student-ticket.create') }}" class="btn btn-primary">
        <i class="fa fa-plus-circle mr-2"></i>新增學生抽獎編號
    </a>
    <a href="{{ route('student-ticket.import') }}" class="btn btn-primary">
        <i class="fa fa-upload mr-2"></i>匯入
    </a>
    {!! Form::open(['route' => ['student-ticket.destroy-all'], 'style' => 'display: inline', 'method' => 'DELETE', 'onSubmit' => "return confirm('確定要全部刪除嗎？');"]) !!}
    <button type="submit" class="btn btn-danger">
        <i class="fa fa-times mr-2"></i>全部刪除
    </button>
    {!! Form::close() !!}

    <a href="{{ route('student-ticket.ticket') }}" class="btn btn-primary" target="_blank">
        <i class="fa fa-external-link-alt mr-2"></i>學生抽獎編號展示
    </a>
@endsection

@section('main_content')
    <div class="alert alert-warning mb-2">
        此功能僅作為社團博覽會無法順利舉行時之備案，正式的抽獎編號請至 {{ link_to_route('ticket.index', '抽獎編號管理') }}
    </div>
    <div class="card">
        <div class="card-body">
            {!! $dataTable->table() !!}
        </div>
    </div>
@endsection

@section('js')
    {!! $dataTable->scripts() !!}
@endsection

resources/views/student-ticket/ticket.blade.php
@extends('layouts.app')

@section('title', '學生抽獎編號')

@section('content')
    <div class="mt-3 pb-3">
        <div class="card">
            <div class="card-body">
                <h1 class="display-3">學生抽獎編號查詢</h1>
                {{ Form::open(['method' => 'get', 'id' => 'ticket_search_form', 'class' => 'form-inline']) }}
                <input type="text" placeholder="學生抽獎編號" id="ticket_search_id" class="form-control mr-sm-2"
                       autocomplete="off">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search mr-2"></i>查詢
                </button>
                {{ Form::close() }}
                <div class="jumbotron text-center mt-3">
                    <h1 class="display-3" id="ticket_number"></h1>
                    <h1 class="display-3" id="ticket_name"></h1>
                    <h1 class="display-3" id="ticket_class"></h1>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(function () {
            var $ticketInfo = $('#ticket_info');
            var $searchIdInput = $('#ticket_search_id');
            var $ticketNumber = $('#ticket_number');
            var $ticketName = $('#ticket_name');
            var $ticketClass = $('#ticket_class');
            var $cat = $('#cat');
            $searchIdInput.focus();
            $cat.hide();
            $('#ticket_search_form').submit(function () {
                //重置搜尋框
                var searchId = $searchIdInput.val();
                $searchIdInput.val('');
                $searchIdInput.focus();
                if (!searchId || $.trim(searchId).length === 0) {
                    return false;
                }
                //重置顯示區
                $cat.hide();
                $ticketNumber.text('');
                $ticketName.text('');
                $ticketClass.text('');
                //檢查ID
                if ($.isNumeric(searchId) === false) {
                    $cat.show();
                    $ticketNumber.text('#' + searchId);
                    $ticketName.html('<span style="color: red">抽獎編號是...數字( ﾟ Дﾟ）</span>');
                    return false;
                }
                //Loading
                $ticketInfo.addClass('loading');
                //透過Ajax查詢
                $.ajax({
                    url: '{{ route('student-ticket.info') }}',
                    type: 'GET',
                    data: {
                        id: searchId
                    },
                    error: function (xhr) {
                        $ticketName.html('<span style="color: red">發生錯誤</span>');
                    },
                    success: function (response) {
                        $ticketNumber.text('#' + response.id);
                        if (response.found) {
                            $ticketName.text(response.name);
                            $ticketClass.text(response.class);
                        } else {
                            $ticketName.html('<span style="color: red">查無此學生抽獎編號</span>');
                            $ticketClass.text('');
                        }
                    },
                    complete: function () {
                        //取消Loading
                        $ticketInfo.removeClass('loading');
                    }
                });
                return false;
            });
        });
    </script>
@endsection