routes/web.php
Route::get('clubs/{club}', 'HomeController@clubsShow')->name('clubs.show');
//地圖
Route::group(['prefix' => 'map'], function () {
    Route::get('/', 'HomeController@clubsStaticMap')->name('clubs.map.static');
    Route::get('google', 'HomeController@clubsGoogleMap')->name('clubs.map.google');
});
//迎新茶會
Route::get('tea-parties', 'TeaPartyController@list')->name('tea-party.list');

//服務條款(含隱私權跟免責)
Route::get('terms', 'TermController@index')->name('terms');
Route::group(['middleware' => ['auth', 'email']], function () {
    Route::post('terms/agree', 'TermController@agree')->name('terms.agree');
});

//常見問題
Route::view('faq', 'misc.faq')->name('faq');

//開發團隊
Route::view('development-team', 'misc.development-team')->name('development-team');

//會員（須完成信箱驗證）
Route::group(['middleware' => ['auth', 'email']], function () {
    //會員管理
    //權限：user.manage、user.view
    Route::resource('user', 'UserController', [
        'except' => [
            'create',
            'store',
        ],
    ]);
    //角色管理
    //權限：role.manage
    Route::group(['middleware' => 'permission:role.manage'], function () {
        Route::resource('role', 'RoleController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //Broadcast Test
    //權限：broadcast.manage
    Route::group(['middleware' => 'permission:broadcast.manage'], function () {
        Route::view('broadcast-test', 'misc.broadcast-test')->name('broadcast-test');
        Route::post('message', 'BroadcastTestController@postMessage')->name('broadcast-test.message');
    });
    //公開測試相關功能
    Route::prefix('open-beta')->group(function () {
        Route::post('promote-to-staff/{club}', 'OpenBetaController@promoteToStaff')->name('open-beta.promote-to-staff');
    });
    //學生管理
    //權限：StudentPolicy
    Route::prefix('student')->group(function () {
        Route::put('fetch/{student}', 'StudentController@fetch')->name('student.fetch');
        Route::get('create-real-student', 'StudentController@createRealStudent')->name('student.create-real-student');
        Route::post('create-real-student', 'StudentController@storeRealStudent')->name('student.store-real-student');
        Route::get('import', 'StudentController@getImport')->name('student.import');
        Route::post('import', 'StudentController@postImport')->name('student.import');
        Route::get('download-import-sample', 'StudentController@downloadImportSample')
            ->name('student.download-import-sample');
    });
    Route::resource('student', 'StudentController');
    //我的聯絡資料
    Route::prefix('my-contact-information')->group(function () {
        Route::get('/', 'MyContactInformationController@index')->name('contact-information.my.index');
        Route::get('edit', 'MyContactInformationController@createOrEdit')
            ->name('contact-information.my.create-or-edit');
        Route::post('/', 'MyContactInformationController@store')
            ->name('contact-information.my.store');
    });
    //聯絡資料管理
    //權限：ContactInformationPolicy
    Route::resource('contact-information', 'ContactInformationController');
    //繳費紀錄管理
    //權限：PaymentRecordPolicy
    Route::post('export/payment-record', 'ExportController@paymentRecord')->name('export.payment-record');
    Route::resource('payment-record', 'PaymentRecordController');
    //QR Code管理
    //權限：qrcode.manage
    Route::group(['middleware' => 'permission:qrcode.manage'], function () {
        //綁定
        Route::get('qrcode/bind', 'QrcodeController@bindForm')->name('qrcode.bind');
        Route::post('qrcode/bind', 'QrcodeController@bind')->name('qrcode.bind');

        Route::resource('qrcode', 'QrcodeController', [
            'only' => [
                'index',
                'show',
            ],
        ]);
    });
    //QR Code集管理
    //權限：qrcode-set.manage
    Route::group(['middleware' => 'permission:qrcode-set.manage'], function () {
        //下載
        Route::post('qrcode-set/{qrcode_set}/download', 'QrcodeSetController@download')->name('qrcode-set.download');

        Route::resource('qrcode-set', 'QrcodeSetController', [
            'only' => [
                'index',
                'create',
                'store',
                'show',
            ],
        ]);
    });
    //攤位管理
    //權限：booth.manage
    Route::group(['middleware' => 'permission:booth.manage'], function () {
        Route::get('booth/import', 'BoothController@getImport')->name('booth.import');
        Route::post('booth/import', 'BoothController@postImport')->name('booth.import');
        Route::get('booth/download-import-sample', 'BoothController@downloadImportSample')
            ->name('booth.download-import-sample');
        Route::resource('booth', 'BoothController');
    });
    //社團類型管理
    //權限：club-type.manage
    Route::group(['middleware' => 'permission:club-type.manage'], function () {
        Route::post('club-type/store-default', 'ClubTypeController@storeDefault')->name('club-type.store-default');
        Route::resource('club-type', 'ClubTypeController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //社團管理
    //權限：club.manage
    Route::group(['middleware' => 'permission:club.manage'], function () {
        Route::get('club/import', 'ClubController@getImport')->name('club.import');
        Route::post('club/import', 'ClubController@postImport')->name('club.import');
        Route::get('club/download-import-sample', 'ClubController@downloadImportSample')
            ->name('club.download-import-sample');
        Route::post('export/club', 'ExportController@club')->name('export.club');
        Route::post('export/club-staff', 'ExportController@clubStaff')->name('export.club-staff');
        Route::group(['prefix' => 'club'], function () {
            Route::resource('data-update-request', 'DataUpdateRequestController', [
                'only' => [
                    'index',
                    'show',
                    'update',
                ],
            ]);
        });
        Route::resource('club', 'ClubController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //茶會管理
    //權限：tea-party.manage
    Route::group(['middleware' => 'permission:tea-party.manage'], function () {
        Route::post('export/tea-party', 'ExportController@teaParty')->name('export.tea-party');
        Route::resource('tea-party', 'TeaPartyController');
    });
    //網站設定
    //權限：setting.manage
    Route::group(['middleware' => 'permission:setting.manage', 'prefix' => 'setting'], function () {
        Route::get('/', 'SettingController@edit')->name('setting.edit');
        Route::post('update', 'SettingController@update')->name('setting.update');
    });
    //ApiKey管理
    //權限：api-key.manage
    Route::group(['middleware' => 'permission:api-key.manage'], function () {
        Route::resource('api-key', 'ApiKeyController', [
            'except' => [
                'show',
                'edit',
                'update',
            ],
        ]);
    });
    //打卡紀錄管理
    //權限：record.manage
    Route::group(['middleware' => 'permission:record.manage'], function () {
        Route::post('export/record', 'ExportController@record')->name('export.record');
        Route::resource('record', 'RecordController', [
            'only' => [
                'index',
            ],
        ]);
    });

    //抽獎編號展示
    Route::group(['middleware' => 'permission:ticket.manage|ticket.show-ticket'], function () {
        Route::get('ticket/ticket', 'TicketController@ticket')->name('ticket.ticket');
    });
    //抽獎編號管理
    //權限：ticket.manage
    Route::group(['middleware' => 'permission:ticket.manage'], function () {
        Route::get('ticket/info', 'TicketController@ticketInfo')->name('ticket.info');
        Route::post('export/ticket', 'ExportController@ticket')->name('export.ticket');
        Route::resource('ticket', 'TicketController', [
            'only' => [
                'index',
            ],
        ]);
    });
    //工作人員抽獎編號展示
    Route::group(['middleware' => 'permission:extra-ticket.manage|extra-ticket.show-ticket'], function () {
        Route::get('extra-ticket/ticket', 'ExtraTicketController@ticket')->name('extra-ticket.ticket');
    });
    //工作人員抽獎編號管理
    //權限：extra-ticket.manage
    Route::group(['middleware' => 'permission:extra-ticket.manage'], function () {
        Route::get('extra-ticket/info', 'ExtraTicketController@ticketInfo')->name('extra-ticket.info');
        Route::get('extra-ticket/import', 'ExtraTicketController@getImport')->name('extra-ticket.import');
        Route::post('extra-ticket/import', 'ExtraTicketController@postImport')->name('extra-ticket.import');
        Route::get('extra-ticket/download-import-sample', 'ExtraTicketController@downloadImportSample')
            ->name('extra-ticket.download-import-sample');
        Route::delete('extra-ticket/destroy-all', 'ExtraTicketController@destroyAll')->name('extra-ticket.destroy-all');
        Route::resource('extra-ticket', 'ExtraTicketController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //學生抽獎編號展示
    Route::group(['middleware' => 'permission:student-ticket.manage|student-ticket.show-ticket'], function () {
        Route::get('student-ticket/ticket', 'StudentTicketController@ticket')->name('student-ticket.ticket');
    });
    //學生抽獎編號管理
    //權限：student-ticket.manage
    Route::group(['middleware' => 'permission:student-ticket.manage'], function () {
        Route::get('student-ticket/info', 'StudentTicketController@ticketInfo')->name('student-ticket.info');
        Route::get('student-ticket/import', 'StudentTicketController@getImport')->name('student-ticket.import');
        Route::post('student-ticket/import', 'StudentTicketController@postImport')->name('student-ticket.import');
        Route::get('student-ticket/download-import-sample', 'StudentTicketController@downloadImportSample')

app/Models/Qrcode.php
<?php

namespace App\Models;

use App\Traits\LegacySerializeDate;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * App\Models\Qrcode
 *
 * @property int $id
 * @property string $code 代碼
 * @property string|null $student_nid 對應學生
 * @property Carbon|null $bind_at 綁定時間
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property int|null $qrcode_set_id
 * @property bool $auto_generated 自動建立
 * @property-read bool $is_last_one 是否為該學生的最後一組 QR Code
 * @property-read string $scan_url 掃描用網址
 * @property-read \App\Models\QrcodeSet|null $qrcodeSet
 * @property-read \App\Models\Student|null $student
 *
 * @method static \Database\Factories\QrcodeFactory factory(...$parameters)
 * @method static Builder|Qrcode newModelQuery()
 * @method static Builder|Qrcode newQuery()
 * @method static Builder|Qrcode query()
 * @method static Builder|Qrcode whereAutoGenerated($value)
 * @method static Builder|Qrcode whereBindAt($value)
 * @method static Builder|Qrcode whereCode($value)
 * @method static Builder|Qrcode whereCreatedAt($value)
 * @method static Builder|Qrcode whereId($value)
 * @method static Builder|Qrcode whereQrcodeSetId($value)
 * @method static Builder|Qrcode whereStudentNid($value)
 * @method static Builder|Qrcode whereUpdatedAt($value)
 * @mixin Eloquent
 */
class Qrcode extends Model
{
    use LegacySerializeDate;
    use HasFactory;

    protected $fillable = [
        'code',
        'student_nid',
        'bind_at',
        'qrcode_set_id',
        'auto_generated',
    ];

    protected $dates = [
        'bind_at',
    ];

    protected $appends = [
        'is_last_one',
    ];

    protected $casts = [
        'auto_generated' => 'bool',
    ];

    /**
     * @return BelongsTo|Builder
     */
    public function student()
    {
        return $this->belongsTo(Student::class, 'student_nid', 'nid');
    }

    /**
     * @return BelongsTo|Builder
     */
    public function qrcodeSet()
    {
        return $this->belongsTo(QrcodeSet::class);
    }

    /**
     * @comment 掃描用網址
     *
     * @return string
     */
    public function getScanUrlAttribute(): string
    {
        return route('qrcode.scan', $this->code);
    }

    /**
     * @comment 是否為該學生的最後一組 QR Code
     *
     * @return bool
     */
    public function getIsLastOneAttribute(): bool
    {
        if (!$this->student) {
            return false;
        }

        return $this->student->qrcode->setAppends([])->id == $this->id;
    }
}

app/Http/Controllers/QrcodeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\QrcodesDataTable;
use App\Models\Qrcode;
use App\Services\StudentService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class QrcodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  QrcodesDataTable  $dataTable
     * @return JsonResponse|Response|View
     */
    public function index(QrcodesDataTable $dataTable)
    {
        return $dataTable->render('qrcode.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Qrcode  $qrcode
     * @return Response
     */
    public function show(Qrcode $qrcode)
    {
        return view('qrcode.show', compact('qrcode'));
    }

    /**
     * 綁定QRCode的表單
     *
     * @return Response
     */
    public function bindForm()
    {
        $qrcodes = Qrcode::with('student')
            ->whereNotNull('student_nid')
            ->whereNotNull('bind_at')
            ->orderBy('bind_at', 'desc')->take(10)->get();

        return view('qrcode.bind', compact('qrcodes'));
    }

    /**
     * 綁定QRCode
     *
     * @param  Request  $request
     * @param  StudentService  $studentService
     * @return RedirectResponse|Response
     *
     * @throws ValidationException
     */
    public function bind(Request $request, StudentService $studentService)
    {
        $this->validate($request, [
            'nid'  => ['required', 'regex:#^[a-zA-Z]\d+$#'],
            'code' => 'required|exists:qrcodes,code',
        ]);

        $nid = trim(strtoupper($request->get('nid')));
        //若以掃描槍輸入，需去除最後一碼
        $nidLength = strlen($nid);
        if (strlen($nid) == 7 || strlen($nid) == 9) {
            $nid = substr($nid, 0, $nidLength - 1);
        }
        //找出學生（若本地沒有，會自動從API找）
        $student = $studentService->findByNid($nid);
        if (!$student) {
            return back()->withErrors(['nid' => '無法找到此學生'])->withInput();
        }

        //找出QRCode
        /** @var Qrcode $qrcode */
        $qrcode = Qrcode::where('code', $request->get('code'))->first();
        if ($qrcode->bind_at) {
            return back()->withErrors(['code' => '代碼無效（已使用過）'])->withInput();
        }

        //綁定
        $student->qrcode()->save($qrcode);

        return back()->with('success', '已綁定');
    }
}

resources/views/qrcode/bind.blade.php
@extends('layouts.base')

@section('title', '綁定 QR Code')

@section('css')
    <style>
        input.upper {
            text-transform: uppercase;
        }
    </style>
@endsection

@section('buttons')
    <a href="{{ route('qrcode.index') }}" class="btn btn-secondary mb-2">
        <i class="fa fa-arrow-left mr-2"></i>QR Code
    </a>
@endsection

@section('main_content')
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    {{ bs()->openForm('post', route('qrcode.bind')) }}
                    {{ bs()->formGroup(bs()->inputGroup(bs()->text('nid')->required()->autofocus())
                    ->suffix(bs()->button(fa()->times())->attributes(['onclick' => "$('input#nid').val('');$('input#nid').focus();return false;"]), false))->class('required')->label('學號')->showAsRow() }}
                    {{ bs()->formGroup(bs()->inputGroup(bs()->text('code')->required()->autofocus())
                    ->suffix(bs()->button(fa()->times())->attributes(['onclick' => "$('input#code').val('');$('input#code').focus();return false;"]), false))->class('required')->label('代號')->showAsRow() }}

                    <div class="row">
                        <div class="mx-auto">
                            {{ bs()->submit('綁定 QR Code', 'primary')->prependChildren(fa()->icon('check')->addClass('mr-2')) }}
                        </div>
                    </div>
                    {{ bs()->closeForm() }}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">綁定紀錄</div>
                <div class="card-body">
                    <ul>
                        @foreach($qrcodes as $qrcode)
                            <li>
                                <span class="badge badge-secondary code">{{ $qrcode->code }}</span>
                                {{ $qrcode->student->display_name }}
                                <br/>
                                <small class="text-muted">
                                    {{ $qrcode->bind_at }}
                                    （{{ $qrcode->bind_at->diffForHumans() }}）
                                </small>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $('form').on('submit', function () {
            //全部轉大寫
            $('input.upper[type=text]').val(function () {
                return this.value.toUpperCase();
            });
            var nidInput = $('input#nid');
            var codeInput = $('input#code');
            //原輸入值
            var nid = nidInput.val();
            var code = codeInput.val();
            //NID簡易正則表達式
            var re = /^[a-zA-Z]\d+$/;
            //若code比nid還像NID
            if (!re.test(nid) && re.test(code)) {
                //交換
                nidInput.val(code);
                codeInput.val(nid);
            }
        });
    </script>
@endsection

resources/views/qrcode/index.blade.php
@extends('layouts.base')

@section('title', 'QR Code')

@section('buttons')
    <a href="{{ route('qrcode.bind') }}" class="btn btn-primary">
        <i class="fa fa-link mr-2"></i>綁定 QR Code
    </a>
    @if(Laratrust::isAbleTo('qrcode-set.manage'))
        <a href="{{ route('qrcode-set.index') }}" class="btn btn-primary">
            <i class="fa fa-list mr-2"></i>QR Code 集
        </a>
    @endif
@endsection

@section('main_content')
    <div class="card">
        <div class="card-body">
            {!! $dataTable->table() !!}
        </div>
    </div>
@endsection

@section('js')
    {!! $dataTable->scripts() !!}
@endsection

resources/views/qrcode/show.blade.php
@extends('layouts.base')

@section('title', $qrcode->code . ' - QR Code')

@section('buttons')
    <a href="{{ route('qrcode.index') }}" class="btn btn-secondary mb-2">
        <i class="fa fa-arrow-left mr-2"></i>QR Code
    </a>
@endsection

@section('main_content')
    <div class="card">
        <div class="card-body text-center">
            <img src="{{ route('code-picture.qrcode', $qrcode->code) }}" class="img-fluid m-2"><br/>
            <img src="{{ route('code-picture.barcode', $qrcode->code) }}" class="img-fluid m-2">
        </div>
        <div class="card-body">
            <dl class="row" style="font-size: 120%">
                <dt class="col-4 col-md-2">代號</dt>
                <dd class="col-8 col-md-10">
                    <span class="code">{{ $qrcode->code }}</span>
                    @if($qrcode->is_last_one)
                        <i class="fa fa-check text-success" title="最後一組"></i>
                    @endif
                </dd>
                <dt class="col-4 col-md-2">自動建立</dt>
                <dd class="col-8 col-md-10">
                    <span class="code">{{ $qrcode->auto_generated ? 'O' : 'X' }}</span>
                </dd>

                <dt class="col-4 col-md-2">學生</dt>
                <dd class="col-8 col-md-10">
                    @if($qrcode->student)
                        @if(Laratrust::isAbleTo('student.manage'))
                            {{ link_to_route('student.show', $qrcode->student->display_name, $qrcode->student) }}
                        @else
                            {{ $qrcode->student->display_name }}
                        @endif
                    @else
                        尚未綁定
                    @endif
                </dd>

                <dt class="col-4 col-md-2">綁定時間</dt>
                <dd class="col-8 col-md-10">
                    @if($qrcode->bind_at)
                        {{ $qrcode->bind_at }}
                        （{{ $qrcode->bind_at->diffForHumans() }}）
                    @else
                        尚未綁定
                    @endif
                </dd>
            </dl>
        </div>
    </div>
@endsection