routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Sitemap
Route::get('sitemap.xml', 'SitemapController@sitemap')->name('sitemap');

//首頁
Route::get('/', 'HomeController@index')->name('index');

//OAuth
Route::group(['prefix' => 'oauth', 'namespace' => 'Auth'], function () {
    Route::get('/', 'OAuthController@index')->name('oauth.index');
    Route::any('login', 'OAuthController@login')->name('oauth.login');
});

//攤位
Route::get('clubs', 'HomeController@clubs')->name('clubs.index');
Route::get('clubs/{club}', 'HomeController@clubsShow')->name('clubs.show');
//地圖
Route::group(['prefix' => 'map'], function () {
    Route::get('/', 'HomeController@clubsStaticMap')->name('clubs.map.static');
    Route::get('google', 'HomeController@clubsGoogleMap')->name('clubs.map.google');
});
//迎新茶會
Route::get('tea-parties', 'TeaPartyController@list')->name('tea-party.list');

//服務條款(含隱私權跟免責)
Route::get('terms', 'TermController@index')->name('terms');
Route::group(['middleware' => ['auth', 'email']], function () {
    Route::post('terms/agree', 'TermController@agree')->name('terms.agree');
});

//常見問題
Route::view('faq', 'misc.faq')->name('faq');

//開發團隊
Route::view('development-team', 'misc.development-team')->name('development-team');

//會員（須完成信箱驗證）
Route::group(['middleware' => ['auth', 'email']], function () {
    //會員管理
    //權限：user.manage、user.view
    Route::resource('user', 'UserController', [
        'except' => [
            'create',
            'store',
        ],
    ]);
    //角色管理
    //權限：role.manage
    Route::group(['middleware' => 'permission:role.manage'], function () {
        Route::resource('role', 'RoleController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //Broadcast Test
    //權限：broadcast.manage
    Route::group(['middleware' => 'permission:broadcast.manage'], function () {
        Route::view('broadcast-test', 'misc.broadcast-test')->name('broadcast-test');
        Route::post('message', 'BroadcastTestController@postMessage')->name('broadcast-test.message');
    });
    //公開測試相關功能
    Route::prefix('open-beta')->group(function () {
        Route::post('promote-to-staff/{club}', 'OpenBetaController@promoteToStaff')->name('open-beta.promote-to-staff');
    });
    //學生管理
    //權限：StudentPolicy
    Route::prefix('student')->group(function () {
        Route::put('fetch/{student}', 'StudentController@fetch')->name('student.fetch');
        Route::get('create-real-student', 'StudentController@createRealStudent')->name('student.create-real-student');
        Route::post('create-real-student', 'StudentController@storeRealStudent')->name('student.store-real-student');
        Route::get('import', 'StudentController@getImport')->name('student.import');
        Route::post('import', 'StudentController@postImport')->name('student.import');
        Route::get('download-import-sample', 'StudentController@downloadImportSample')
            ->name('student.download-import-sample');
    });
    Route::resource('student', 'StudentController');
    //我的聯絡資料
    Route::prefix('my-contact-information')->group(function () {
        Route::get('/', 'MyContactInformationController@index')->name('contact-information.my.index');
        Route::get('edit', 'MyContactInformationController@createOrEdit')
            ->name('contact-information.my.create-or-edit');
        Route::post('/', 'MyContactInformationController@store')
            ->name('contact-information.my.store');
    });
    //聯絡資料管理
    //權限：ContactInformationPolicy
    Route::resource('contact-information', 'ContactInformationController');
    //繳費紀錄管理
    //權限：PaymentRecordPolicy
    Route::post('export/payment-record', 'ExportController@paymentRecord')->name('export.payment-record');
    Route::resource('payment-record', 'PaymentRecordController');
    //QR Code管理
    //權限：qrcode.manage
    Route::group(['middleware' => 'permission:qrcode.manage'], function () {
        //綁定
        Route::get('qrcode/bind', 'QrcodeController@bindForm')->name('qrcode.bind');
        Route::post('qrcode/bind', 'QrcodeController@bind')->name('qrcode.bind');

        Route::resource('qrcode', 'QrcodeController', [
            'only' => [
                'index',
                'show',
            ],
        ]);
    });
    //QR Code集管理
    //權限：qrcode-set.manage
    Route::group(['middleware' => 'permission:qrcode-set.manage'], function () {
        //下載
        Route::post('qrcode-set/{qrcode_set}/download', 'QrcodeSetController@download')->name('qrcode-set.download');

        Route::resource('qrcode-set', 'QrcodeSetController', [
            'only' => [
                'index',
                'create',
                'store',
                'show',
            ],
        ]);
    });
    //攤位管理
    //權限：booth.manage
    Route::group(['middleware' => 'permission:booth.manage'], function () {
        Route::get('booth/import', 'BoothController@getImport')->name('booth.import');
        Route::post('booth/import', 'BoothController@postImport')->name('booth.import');
        Route::get('booth/download-import-sample', 'BoothController@downloadImportSample')
            ->name('booth.download-import-sample');
        Route::resource('booth', 'BoothController');
    });
    //社團類型管理
    //權限：club-type.manage
    Route::group(['middleware' => 'permission:club-type.manage'], function () {
        Route::post('club-type/store-default', 'ClubTypeController@storeDefault')->name('club-type.store-default');
        Route::resource('club-type', 'ClubTypeController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //社團管理
    //權限：club.manage
    Route::group(['middleware' => 'permission:club.manage'], function () {
        Route::get('club/import', 'ClubController@getImport')->name('club.import');
        Route::post('club/import', 'ClubController@postImport')->name('club.import');
        Route::get('club/download-import-sample', 'ClubController@downloadImportSample')
            ->name('club.download-import-sample');
        Route::post('export/club', 'ExportController@club')->name('export.club');
        Route::post('export/club-staff', 'ExportController@clubStaff')->name('export.club-staff');
        Route::group(['prefix' => 'club'], function () {
            Route::resource('data-update-request', 'DataUpdateRequestController', [
                'only' => [
                    'index',
                    'show',
                    'update',
                ],
            ]);
        });
        Route::resource('club', 'ClubController', [
            'except' => [
                'show',
            ],
        ]);
    });
    //茶會管理
    //權限：tea-party.manage
    Route::group(['middleware' => 'permission:tea-party.manage'], function () {
        Route::post('export/tea-party', 'ExportController@teaParty')->name('export.tea-party');
        Route::resource('tea-party', 'TeaPartyController');
    });
    //網站設定
    //權限：setting.manage
    Route::group(['middleware' => 'permission:setting.manage', 'prefix' => 'setting'], function () {
        Route::get('/', 'SettingController@edit')->name('setting.edit');
        Route::post('update', 'SettingController@update')->name('setting.update');
    });
    //ApiKey管理
    //權限：api-key.manage
    Route::group(['middleware' => 'permission:api-key.manage'], function () {
        Route::resource('api-key', 'ApiKeyController', [
            'except' => [
                'show',
                'edit',
                'update',
            ],
        ]);
    });
    //打卡紀錄管理
    //權限：record.manage
    Route::group(['middleware' => 'permission:record.manage'], function () {
        Route::post('export/record', 'ExportController@record')->name('export.record');
        Route::resource('record', 'RecordController', [
            'only' => [
                'index',
            ],
        ]);
    });

    //抽獎編號展示
    Route::group(['middleware' => 'permission:ticket.manage|ticket.show-ticket'], function () {
        Route::get('ticket/ticket', 'TicketController@ticket')->name('ticket.ticket');
    });
    //抽獎編號管理
    //權限：ticket.manage
    Route::group(['middleware' => 'permission:ticket.manage'], function () {
        Route::get('ticket/info', 'TicketController@ticketInfo')->name('ticket.info');
        Route::post('export/ticket', 'ExportController@ticket')->name('export.ticket');
        Route::resource('ticket', 'TicketController', [
            'only' => [
                'index',
            ],
        ]);
    });
    //工作人員抽獎編號展示
    Route::group(['middleware' => 'permission:extra-ticket.manage|extra-ticket.show-ticket'], function () {
        Route::get('extra-ticket/ticket', 'ExtraTicketController@ticket')->name('extra-ticket.ticket');
    });
    //工作人員抽獎編號管理
    //權限：extra-ticket.manage
    Route::group(['middleware' => 'permission:extra-ticket.manage'], function () {
        Route::get('extra-ticket/info', 'ExtraTicketController@ticketInfo')->name('extra-ticket.info');
        Route::get('extra-ticket/import', 'ExtraTicketController@getImport')->name('extra-ticket.import');
        Route::post('extra-ticket/import', 'ExtraTicketController@postImport')->name('extra-ticket.import');
        Route::get('extra-ticket/download-import-sample', 'ExtraTicketController@downloadImportSample')
            ->name('extra-ticket.download-import-sample');
        Route::delete('extra-ticket/destroy-all', 'ExtraTicketController@destroyAll')->name('extra-ticket.destroy-all');
        Route::resource('extra-ticket', 'ExtraTicketController', [
            'except' => [
                'show',
            ],
        ]);
    });

app/Models/Club.php
<?php

namespace App\Models;

use App\Traits\LegacySerializeDate;
use App\Traits\LogModelEvent;
use Dyrynda\Database\Support\NullableFields;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Support\Carbon;

/**
 * App\Models\Club
 *
 * @property int $id
 * @property int|null $club_type_id 社團類型
 * @property string|null $number 社團編號
 * @property string $name 名稱
 * @property string|null $description 簡介
 * @property string|null $url 網址
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property string|null $extra_info 額外資訊
 * @property string|null $custom_question 自訂問題
 * @property-read Collection|\App\Models\ActivityLog[] $activities
 * @property-read int|null $activities_count
 * @property-read Collection|\App\Models\Booth[] $booths
 * @property-read int|null $booths_count
 * @property-read \App\Models\ClubSurvey|null $clubSurvey
 * @property-read \App\Models\ClubType|null $clubType
 * @property-read Collection|\App\Models\DataUpdateRequest[] $dataUpdateRequests
 * @property-read int|null $data_update_requests_count
 * @property-read Collection|\App\Models\User[] $favoriteBy
 * @property-read int|null $favorite_by_count
 * @property-read Collection|\App\Models\Feedback[] $feedback
 * @property-read int|null $feedback_count
 * @property-read string $display_name 顯示名稱
 * @property-read bool $is_counted 是否列入抽獎集點
 * @property-read \App\Models\ImgurImage|null $imgurImage
 * @property-read Collection|\App\Models\Student[] $leaders
 * @property-read int|null $leaders_count
 * @property-read Collection|\App\Models\PaymentRecord[] $paymentRecords
 * @property-read int|null $payment_records_count
 * @property-read Collection|\App\Models\Record[] $records
 * @property-read int|null $records_count
 * @property-read Collection|\App\Models\Student[] $staffs
 * @property-read int|null $staffs_count
 * @property-read Collection|\App\Models\Student[] $students
 * @property-read int|null $students_count
 * @property-read \App\Models\TeaParty|null $teaParty
 * @property-read Collection|\App\Models\User[] $users
 * @property-read int|null $users_count
 *
 * @method static \Database\Factories\ClubFactory factory(...$parameters)
 * @method static Builder|Club newModelQuery()
 * @method static Builder|Club newQuery()
 * @method static Builder|Club query()
 * @method static Builder|Club whereClubTypeId($value)
 * @method static Builder|Club whereCreatedAt($value)
 * @method static Builder|Club whereCustomQuestion($value)
 * @method static Builder|Club whereDescription($value)
 * @method static Builder|Club whereExtraInfo($value)
 * @method static Builder|Club whereId($value)
 * @method static Builder|Club whereName($value)
 * @method static Builder|Club whereNumber($value)
 * @method static Builder|Club whereUpdatedAt($value)
 * @method static Builder|Club whereUrl($value)
 * @mixin Eloquent
 */
class Club extends Model
{
    use LogModelEvent;
    use LegacySerializeDate;
    use NullableFields;
    use HasFactory;

    protected $fillable = [
        'name',
        'number',
        'club_type_id',
        'description',
        'extra_info',
        'url',
        'custom_question',
    ];

    protected $nullable = [
        'description',
        'url',
    ];

    protected $appends = [
        'is_counted',
    ];

    protected $hidden = [
        'extra_info',
    ];

    /**
     * @return array
     */
    public static function selectOptions()
    {
        $options = [null => '&nbsp;'];

        $clubs = static::all();
        $clubTypes = ClubType::has('clubs', '>', 0)->get();
        foreach ($clubTypes as $clubType) {
            $options[$clubType->name] = $clubs->where('club_type_id', $clubType->id)->pluck('name', 'id')->toArray();
        }
        $options += $clubs->where('club_type_id', null)->pluck('name', 'id')->toArray();

        return $options;
    }

    /**
     * @return BelongsTo|Builder
     */
    public function clubType()
    {
        return $this->belongsTo(ClubType::class);
    }

    /**
     * @return HasMany|Builder
     */
    public function booths()
    {
        return $this->hasMany(Booth::class);
    }

    /**
     * @return HasMany|Builder
     */
    public function records()
    {
        return $this->hasMany(Record::class);
    }

    /**
     * @return HasMany|Builder
     */
    public function feedback()
    {
        return $this->hasMany(Feedback::class);
    }

    /**
     * @return HasMany|Builder
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }

    /**
     * @return MorphOne
     */
    public function imgurImage()
    {
        return $this->morphOne(ImgurImage::class, 'club');
    }

    /**
     * @return HasMany|Builder
     */
    public function dataUpdateRequests()
    {
        return $this->hasMany(DataUpdateRequest::class)->orderByDesc('submit_at');
    }

    /**
     * @return HasOne
     */
    public function clubSurvey()
    {
        return $this->hasOne(ClubSurvey::class);
    }

    /**
     * @return HasOne
     */
    public function teaParty()
    {
        return $this->hasOne(TeaParty::class);
    }

    /**
     * @return BelongsToMany
     */
    public function students()
    {
        return $this->belongsToMany(Student::class)->withTimestamps()->withPivot('is_leader');
    }

    /**
     * @return BelongsToMany
     */
    public function staffs()
    {
        return $this->belongsToMany(Student::class)->withTimestamps()->wherePivot('is_leader', false);
    }

    /**
     * @return BelongsToMany
     */
    public function leaders()
    {
        return $this->belongsToMany(Student::class)->withTimestamps()->wherePivot('is_leader', true);
    }

    /**
     * @return BelongsToMany
     */
    public function favoriteBy()
    {
        return $this->belongsToMany(User::class, 'favorite_club')->withTimestamps();
    }

    public function paymentRecords()
    {
        return $this->hasMany(PaymentRecord::class);
    }

    /**
     * @comment 是否列入抽獎集點
     *
     * @return bool
     */
    public function getIsCountedAttribute(): bool
    {
        if (!$this->clubType) {
            return false;
        }

        return $this->clubType->is_counted;
    }

    /**
     * @comment 顯示名稱
     *
     * @return string
     */
    public function getDisplayNameAttribute(): string
    {
        $html = '';
        if ($this->clubType) {
            $html .= $this->clubType->tag . ' ';
        }
        $html .= $this->name;

        return $html;
    }

    protected function getNameForActivityLog(): string
    {
        return $this->name;
    }
}

resources/views/club/create.blade.php
@extends('layouts.base')

@section('title', '新增社團')

@section('buttons')
    <a href="{{ route('club.index') }}" class="btn btn-secondary">
        <i class="fa fa-arrow-left mr-2"></i>社團管理
    </a>
@endsection

@section('main_content')
    <div class="card">
        <div class="card-body">
            {{ bs()->openForm('post', route('club.store'), ['files' => true]) }}
            @include('club.form')

            <div class="row">
                <div class="mx-auto">
                    {{ bs()->submit('確認', 'primary')->prependChildren(fa()->icon('check')->addClass('mr-2')) }}
                </div>
            </div>
            {{ bs()->closeForm() }}
        </div>
    </div>
@endsection

resources/views/club/edit.blade.php
@extends('layouts.base')

@section('title', '編輯社團')

@section('buttons')
    <a href="{{ route('clubs.show', $club) }}" class="btn btn-secondary">
        <i class="fa fa-arrow-left mr-2"></i>返回
    </a>
@endsection

@section('main_content')
    <div class="card">
        <div class="card-body">
            {{ bs()->openForm('patch', route('club.update', $club), ['model' => $club, 'files' => true]) }}
            @include('club.form')

            <div class="row">
                <div class="mx-auto">
                    {{ bs()->submit('確認', 'primary')->prependChildren(fa()->icon('check')->addClass('mr-2')) }}
                </div>
            </div>
            {{ bs()->closeForm() }}
        </div>
    </div>
@endsection

resources/views/club/form.blade.php
{{ bs()->formGroup(bs()->text('number')->placeholder('如：A66'))->label('社團編號')->showAsRow() }}
{{ bs()->formGroup(bs()->text('name')->placeholder('如：黑客社')->required())->class('required')->label('名稱')->showAsRow() }}
{{ bs()->formGroup(bs()->select('club_type_id')->options(\App\Models\ClubType::selectOptions()))->label('社團類型')->showAsRow() }}
<hr/>
{{ bs()->formGroup(bs()->textarea('description')->attribute('rows', 10)->class('tinymce'))->label('描述')->showAsRow() }}
{{ bs()->formGroup(bs()->textarea('extra_info')->attribute('rows', 10)->class('tinymce'))->label('額外資訊')->helpText('僅限對此社團填寫回饋資料的學生檢視，可放FB社團、LINE群網址等')->showAsRow() }}
{{ bs()->formGroup(bs()->input('url', 'url')->placeholder('網站、粉絲專頁等'))->label('網址')->showAsRow() }}

@if(isset($club) && $club->imgurImage)
    <div class="form-group row">
        <label for="image_file" class="col-md-2 col-form-label">圖片</label>
        <div class="col-md-10">
            <p class="form-control-plaintext">
                <img src="{{ $club->imgurImage->thumbnail('t') }}" alt="Club image">
                <a href="{{ $club->imgurImage->url }}" target="_blank">
                    {{ $club->imgurImage->file_name }}
                </a>
            </p>
            <small class="form-text text-muted">
                若不更換圖片，下欄請留空
            </small>
        </div>
    </div>
@endif

{{ bs()->formGroup(bs()->simpleFile('image_file')->acceptImage())->label('圖片上傳')
->helpText('檔案大小限制：'. app(\App\Services\FileService::class)->imgurUploadMaxSize())->showAsRow() }}
{{ bs()->formGroup(bs()->text('custom_question'))->label('自訂問題')
->helpText('學生填寫回饋資料時，可一併詢問一個問題')->showAsRow() }}
<hr/>
{{ bs()->formGroup(bs()->select('booth_id[]')->attributes(['id' => 'booth_id', 'multiple']))->label('攤位')->showAsRow() }}
{{ bs()->formGroup(bs()->select('leader_nid'))->label('社長')->showAsRow() }}
{{ bs()->formGroup(bs()->select('staff_nid[]')->attributes(['id' => 'staff_nid', 'multiple']))->label('攤位工作人員')->showAsRow() }}

@section('js')
    @parent
    @include('components.tinymce')
    <script>
        $(function () {
            function formatTemplateBooth(booth) {
                if (booth.loading) return booth.text;
                if (!booth.name) return null;

                var markup =  booth.name;
                if(booth.club){
                    markup += ' <span class="badge badge-warning">' + booth.club + '</span>'
                }
                return markup;
            }

            function formatTemplateStudent(student) {
                if (student.loading) return student.text;
                if (!student.name) return null;

                var markup =  '<span class="badge badge-secondary">' + student.id + '</span> ' + student.name;
                if(student.club){
                    markup += ' <span class="badge badge-warning">' + student.club + '</span>'
                }
                return markup;
            }

            function formatTemplateSelection(item) {
                return item.name || item.text;
            }

            var $boothSelect = $('#booth_id');
            var selectedBooth = {!! isset($club) ? $club->booths->pluck('name', 'id')->toJson() : '{}' !!};
            var initialBooths = [];
            $.each(selectedBooth, function (key, val) {
                initialBooths.push({id: key, text: val});
            });
            $boothSelect.select2({
                tags: true,
                tokenSeparators: [',', ' '],
                data: initialBooths,
                ajax: {
                    url: '{{ route('api.booth-list') }}',
                    type: 'POST',
                    headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content'),
                        'Accept': 'application/json'
                    },
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            q: params.term, // search term
                            page: params.page,
                            club: {{ $club->id ?? 0 }}
                        };
                    },
                    processResults: function (data, params) {
                        params.page = params.page || 1;
                        return {
                            results: data.items,
                            pagination: {
                                more: params.page < data.last_page
                            }
                        };
                    },
                    cache: true
                },
                minimumInputLength: 0,
                escapeMarkup: function (markup) {
                    return markup;
                }, // let our custom formatter work
                templateResult: formatTemplateBooth, // omitted for brevity, see the source of this page
                templateSelection: formatTemplateSelection // omitted for brevity, see the source of this page
            });
            $boothSelect.val(Object.keys(selectedBooth)).trigger('change');

            var studentSelect2Options = {
                tokenSeparators: [',', ' '],
                ajax: {
                    url: '{{ route('api.club-student-list') }}',
                    type: 'POST',
                    headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content'),
                        'Accept': 'application/json'
                    },
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            q: params.term, // search term
                            page: params.page,
                            club: {{ $club->id ?? 0 }}
                        };
                    },
                    processResults: function (data, params) {
                        params.page = params.page || 1;
                        return {
                            results: data.items,
                            pagination: {
                                more: params.page < data.last_page
                            }
                        };
                    },
                    cache: true
                },
                minimumInputLength: 0,
                escapeMarkup: function (markup) {
                    return markup;
                }, // let our custom formatter work
                templateResult: formatTemplateStudent, // omitted for brevity, see the source of this page
                templateSelection: formatTemplateSelection // omitted for brevity, see the source of this page
            };
            var selectedLeaders = {!! isset($club) ? $club->leaders->pluck('name', 'nid')->toJson() : '{}' !!};
            var initialLeaders = [];
            $.each(selectedLeaders, function (key, val) {
                initialLeaders.push({id: key, text: val});
            });
            var $leaderSelect = $('#leader_nid');
            $leaderSelect.select2($.extend({}, studentSelect2Options, {
                placeholder: '',
                allowClear: true,
                data: initialLeaders,
            }));
            $leaderSelect.val(Object.keys(selectedLeaders)).trigger('change');

            var selectedStaffs = {!! isset($club) ? $club->staffs->pluck('name', 'nid')->toJson() : '{}' !!};
            var initialStaffs = [];
            $.each(selectedStaffs, function (key, val) {
                initialStaffs.push({id: key, text: val});
            });
            var $staffSelect = $('#staff_nid');
            $staffSelect.select2($.extend({}, studentSelect2Options, {
                tags: true,
                data: initialStaffs,
            }));
            $staffSelect.val(Object.keys(selectedStaffs)).trigger('change');
        });
    </script>
@endsection

resources/views/club/index.blade.php
@extends('layouts.base')

@section('title', '社團管理')

@section('buttons')
    <a href="{{ route('club.create') }}" class="btn btn-primary">
        <i class="fa fa-plus-circle mr-2"></i>新增社團
    </a>
    <a href="{{ route('club.import') }}" class="btn btn-primary">
        <i class="fa fa-upload mr-2"></i>匯入
    </a>
    {!! Form::open(['route' => ['export.club'], 'style' => 'display: inline']) !!}
    <button type="submit" class="btn btn-success">
        <i class="fa fa-download mr-2"></i>匯出社團
    </button>
    {!! Form::close() !!}
    {!! Form::open(['route' => ['export.club-staff'], 'style' => 'display: inline']) !!}
    <button type="submit" class="btn btn-success">
        <i class="fa fa-download mr-2"></i>匯出攤位負責人
    </button>
    {!! Form::close() !!}
@endsection

@section('main_content')
    <div class="card">
        <div class="card-body">
            {!! $dataTable->table() !!}
        </div>
    </div>
@endsection

@section('js')
    {!! $dataTable->scripts() !!}
@endsection